feat: add check for max number of characters for model name
juju/names pull request #115
Opened 2024-11-15 13:44 UTC by SimoneDutto

This PR adds a check for a maximum number of characters for model name.

This is to address this bug: https://bugs.launchpad.net/juju/+bug/2080003

> I could have made the same check by changing the regular expression, but I think it's better to check it directly with `len` because it's clearer and more performant. But I am open to hearing your opinion.

2024-11-15 15:50 UTC, SimoneDutto commented
After a discussion with @nvinuesa I have made some tests to find our implicit limit model name as of today:
`max_char_now = 255 - num_char("<model_owner_id>-<6longid>.log") = 238`
A model with a name longer than 238 characters will break the modelmanager, the model is created w/o errors but you can't deploy anything.


Test#1 (normal length):
![image](https://github.com/user-attachments/assets/73cf9cfd-babb-4501-abb8-571b34d84c08)

All good
Test#2 (max length):
![image](https://github.com/user-attachments/assets/4b695bd7-77af-4e04-a276-7912486c27bf)

All good

Test#3 (over max length):
![image](https://github.com/user-attachments/assets/4a213cc5-c8aa-422f-b346-a80422963326)
Stuck in allocating with this error in the `controller` model:
```
machine-0: 16:42:15 ERROR juju.workers.modelworkermanager exited "f9f7e580-ccc0-4570-8d03-1fbcb8418c3b": cannot manage model "admin-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" (f9f7e580-ccc0-4570-8d03-1fbcb8418c3b): unable to prime log file: open /var/log/juju/models/admin-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-f9f7e5.log: file name too long
```

What do you think can be a good maximum characters to avoid errors during juju upgrade but not being too close to the limit?

2024-11-15 16:38 UTC, nvinuesa commented
@SimoneDutto nice investigation! Regarding the actual number to use I'd say something like 128 (that should give us some margin and I don't think anyone should be doing 128 chars length model names anyways) but I'd love to get inputs from @jameinel or @manadart because I don't know if there are some usecases I'm missing.

2024-11-18 13:47 UTC, manadart commented
Yeah, I like the powers of 2. I say 128.

2024-11-18 16:48 UTC, SimonRichardson requested changes
This is a breaking change and should be a new version.

2024-11-21 11:19 UTC, closed without merging

2024-11-21 11:19 UTC, SimoneDutto commented
Closing because the scope of this issue is wider than expected.
---
We'll evaluate a way to validate user inputs in a broader-scope discussion and come back to it.